version: '3.8'

services:
  omni_postgres:
    image: postgres:15-alpine
    container_name: omni_postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=engineer
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=data_warehouse
    volumes:
      - omni_dw_data:/var/lib/postgresql/data
    networks:
      - omni_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U engineer -d data_warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  omni_metabase:
    image: metabase/metabase:latest
    container_name: omni_metabase
    user: "root"
    ports:
      - "3050:3000"
    depends_on:
      omni_postgres:
        condition: service_healthy
    environment:                           
      - MB_DB_FILE=/metabase-data/metabase.db 
    volumes:                               
      - omni_metabase_data:/metabase-data
    networks:
      - omni_network

  omni_prefect:
    image: prefecthq/prefect:3-latest
    container_name: omni_prefect
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_UI_API_URL=http://localhost:4205/api
    ports:
      - "4205:4200"
    networks:
      - omni_network

  omni_jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: omni_jupyter
    user: root
    environment:
      - JUPYTER_TOKEN=prefect
      - IN_DOCKER=true
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8890:8888"
    networks:
      - omni_network

  omni_elt_runner:
    build: .
    container_name: omni_elt_runner
    depends_on:
      omni_postgres:
        condition: service_healthy
      omni_prefect:
        condition: service_started
    environment:
      - PREFECT_API_URL=http://omni_prefect:4200/api
      - IN_DOCKER=true
      - POSTGRES_USER=engineer
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=data_warehouse
    networks:
      - omni_network

volumes:
  omni_dw_data:
  omni_metabase_data: 

networks:
  omni_network:
    driver: bridge
